"""Scope validation, pinned local DNS and output redaction."""

import hashlib
import ipaddress
import re
import socket
from urllib.parse import parse_qsl, urlencode, urljoin, urlsplit, urlunsplit


class ScopeError(ValueError):
    pass


PRIVATE_NETWORKS = tuple(ipaddress.ip_network(n) for n in (
    "127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7",
))
SECRET_KEY = re.compile(r"pass|secret|token|session|auth|cookie|api.?key|credential|csrf|xsrf", re.I)
CPF_PATTERN = re.compile(r"(?<![\w])(?:[0-9]{3}\.[0-9]{3}\.[0-9]{3}-[0-9]{2}|[0-9]{11})(?![\w])")
DANGEROUS = re.compile(r"(?:^|[/_?=&\s-])(logout|logoff|signout|sign-out|delete|remove|destroy|reset|purchase|checkout|pay|unsubscribe)(?:$|[/_?=&\s-])", re.I)


def local_ip(address: str) -> bool:
    ip = ipaddress.ip_address(address)
    if isinstance(ip, ipaddress.IPv6Address) and ip.ipv4_mapped:
        ip = ip.ipv4_mapped
    return any(ip.version == network.version and ip in network for network in PRIVATE_NETWORKS)


def canonical(url: str, base: str = "") -> str:
    value = urljoin(base, url.strip())
    if any(ord(c) < 32 for c in value) or "\\" in value:
        raise ScopeError("Invalid URL characters")
    p = urlsplit(value)
    if p.scheme not in ("http", "https") or not p.hostname or p.username is not None or p.password is not None:
        raise ScopeError("Only HTTP(S) URLs without embedded credentials are allowed")
    host = p.hostname.encode("idna").decode().lower()
    port = p.port or (443 if p.scheme == "https" else 80)
    if not 1 <= port <= 65535:
        raise ScopeError("Invalid port")
    authority = f"[{host}]" if ":" in host else host
    if port != (443 if p.scheme == "https" else 80):
        authority += f":{port}"
    return urlunsplit((p.scheme, authority, p.path or "/", p.query, ""))


def origin(url: str) -> str:
    p = urlsplit(canonical(url))
    return f"{p.scheme}://{p.netloc}"


class Scope:
    def __init__(self, base: str):
        self.base = canonical(base)
        self.origin = origin(self.base)
        p = urlsplit(self.base)
        self.host, self.port = p.hostname, p.port or (443 if p.scheme == "https" else 80)
        addresses = list(dict.fromkeys(info[4][0] for info in socket.getaddrinfo(
            self.host, self.port, type=socket.SOCK_STREAM,
        )))
        if not addresses or not all(local_ip(ip) for ip in addresses):
            raise ScopeError("Target must resolve exclusively to loopback or private local-network addresses")
        self.addresses = addresses  # Resolve once, connect only to these IPs: no rebinding.

    def check(self, url: str) -> str:
        url = canonical(url, self.base)
        if origin(url) != self.origin:
            raise ScopeError("Cross-origin request blocked")
        return url


class Redactor:
    def __init__(self, *secrets: str):
        self.secrets = {s for s in secrets if s}

    def add(self, value: str):
        if value:
            self.secrets.add(value)
            if value.lower().startswith("bearer "):
                self.secrets.add(value[7:])

    def text(self, value: str) -> str:
        for secret in sorted(self.secrets, key=len, reverse=True):
            if len(secret) < 4:
                value = re.sub(r"(?<!\w)" + re.escape(secret) + r"(?!\w)", "[REDACTED]", value)
            else:
                value = value.replace(secret, "[REDACTED]")
        def mask_url(match):
            try:
                p = urlsplit(match[0])
                query = urlencode([(k, "[REDACTED]") for k, _ in parse_qsl(p.query, keep_blank_values=True)])
                return urlunsplit((p.scheme, p.netloc.rsplit("@", 1)[-1], p.path, query, ""))
            except ValueError:
                return "[URL REDACTED]"
        value = re.sub(r'''https?://[^\s<>"']+''', mask_url, value)
        value = CPF_PATTERN.sub("[CPF REDACTED]", value)
        value = re.sub(r"[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}", "[EMAIL REDACTED]", value)
        value = re.sub(r"(?i)(bearer\s+)[\w.~-]+", r"\1[REDACTED]", value)
        return value

    def url(self, value: str) -> str:
        try:
            p = urlsplit(value)
        except ValueError:
            return "[INVALID URL]"
        # Query values can contain PII, IDs, signed URLs or secrets, regardless of key name.
        query = urlencode([(k, "[REDACTED]") for k, _ in parse_qsl(p.query, keep_blank_values=True)])
        return self.text(urlunsplit((p.scheme, p.netloc.rsplit("@", 1)[-1], p.path, query, "")))

    def clean(self, value):
        if isinstance(value, dict):
            # Structural enums/IDs are generated by code, not data containing credentials.
            structural = {"schema_version", "status", "severity", "confidence", "provider", "method", "type", "cwe", "session", "access_context", "action_id", "id", "tool", "source", "mode", "confirmed_methods", "declared_methods"}
            return {k: v if k in structural or (k == "value" and v == "[CPF REDACTED]") else self.clean(v) for k, v in value.items()}
        if isinstance(value, list):
            return [self.clean(v) for v in value]
        if isinstance(value, str):
            if value.startswith(("http://", "https://")):
                return self.url(value)
            return self.text(value)
        return value


def fingerprint(value: str) -> str:
    return hashlib.sha256(value.encode()).hexdigest()[:16]
